[package]
name = "collector"
version = "0.1.0"
edition = "2024"

[dependencies]
shared_data = { path = "../shared_data" }
sysinfo = { version = "0.37.2", features = ["apple-app-store"] }
thiserror = "2.0.17"
uuid = { version = "1.18.1", features = ["fast-rng", "v4"] }
