[package]
name = "shared_data"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = { version = "2.0.1", features = ["serde"] }
crc32fast = "1.5.0"
serde = { version = "1.0.228", features = ["derive"] }
# serde_json = "1.0.145"
