[package]
name = "tokio_console"
version = "0.1.0"
edition = "2024"


[dependencies]
anyhow = "1.0.100"
console-subscriber = "0.5.0"
tokio = { version = "1.48.0", features = ["full"] }
tracing = "0.1.41"
